"""
Live Segmentation Module — YOLOv8-seg (REAL-TIME)
Trained on data generated by the data prep pipeline.
Runs at 30+ FPS for live inference.
"""

import numpy as np
import cv2
from typing import List, Optional
from dataclasses import dataclass, field

from config import (
    DEVICE, YOLO_MODEL_PATH, YOLO_CONF_THRESHOLD,
    YOLO_IOU_THRESHOLD, MASK_ALPHA, ACTIVITY_COLORS
)


@dataclass
class OtterDetection:
    """Single otter detection with mask and metadata."""
    mask: Optional[np.ndarray] = None   # Binary mask (H, W)
    bbox: np.ndarray = field(default_factory=lambda: np.zeros(4))  # [x1, y1, x2, y2]
    confidence: float = 0.0
    cropped_image: Optional[np.ndarray] = None
    otter_id: int = 0
    activity: str = "unknown"
    activity_conf: float = 0.0
    held_object: str = "none"
    object_conf: float = 0.0


class LiveSegmenter:
    """
    YOLOv8-seg model trained on otter data.
    Fast enough for real-time inference (30+ FPS on GPU).
    """

    def __init__(self, device: str = DEVICE):
        self.device = device
        self.model = None
        self._loaded = False

    def load_model(self, model_path: str = str(YOLO_MODEL_PATH)):
        """Load the trained YOLOv8-seg model."""
        if self._loaded:
            return

        print(f"[LiveSeg] Loading YOLOv8-seg from {model_path}...")
        try:
            from ultralytics import YOLO
            self.model = YOLO(model_path)
            # Warm up
            self.model.predict(
                np.zeros((640, 640, 3), dtype=np.uint8),
                verbose=False, device=self.device
            )
            print("[LiveSeg] YOLOv8-seg loaded and warmed up.")
            self._loaded = True
        except FileNotFoundError:
            print(f"[LiveSeg] Model not found at {model_path}")
            print("[LiveSeg] Train the model first: python run.py --train-yolo")
            self.model = None
        except Exception as e:
            print(f"[LiveSeg] Error loading model: {e}")
            self.model = None

    def segment_frame(self, frame: np.ndarray) -> List[OtterDetection]:
        """
        Run YOLOv8-seg on a frame. Returns list of otter detections with masks.
        """
        if self.model is None:
            return []

        results = self.model.predict(
            frame,
            conf=YOLO_CONF_THRESHOLD,
            iou=YOLO_IOU_THRESHOLD,
            verbose=False,
            device=self.device,
        )

        detections = []
        result = results[0]

        if result.boxes is None or len(result.boxes) == 0:
            return []

        for i, box in enumerate(result.boxes):
            x1, y1, x2, y2 = map(int, box.xyxy[0].cpu().numpy())
            conf = float(box.conf[0])

            # Clamp to frame bounds
            h, w = frame.shape[:2]
            x1, y1 = max(0, x1), max(0, y1)
            x2, y2 = min(w, x2), min(h, y2)

            # Get segmentation mask if available
            mask = None
            if result.masks is not None and i < len(result.masks):
                mask_data = result.masks[i].data[0].cpu().numpy()
                mask = cv2.resize(mask_data, (w, h))
                mask = (mask > 0.5).astype(np.uint8)

            # Crop otter region
            crop = frame[y1:y2, x1:x2].copy()
            if crop.size == 0:
                continue

            detections.append(OtterDetection(
                mask=mask,
                bbox=np.array([x1, y1, x2, y2]),
                confidence=conf,
                cropped_image=crop,
                otter_id=i,
            ))

        return detections

    def draw_detections(
        self,
        frame: np.ndarray,
        detections: List[OtterDetection],
        show_mask: bool = True,
        show_labels: bool = True,
    ) -> np.ndarray:
        """Draw segmentation masks and labels on frame."""
        overlay = frame.copy()

        for det in detections:
            color = ACTIVITY_COLORS.get(det.activity, (200, 200, 200))
            color_bgr = (color[2], color[1], color[0])

            # Draw mask
            if show_mask and det.mask is not None and det.mask.shape == frame.shape[:2]:
                mask_region = det.mask.astype(bool)
                overlay[mask_region] = (
                    np.array(color_bgr) * MASK_ALPHA +
                    overlay[mask_region] * (1 - MASK_ALPHA)
                ).astype(np.uint8)

                contours, _ = cv2.findContours(
                    det.mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
                )
                cv2.drawContours(overlay, contours, -1, color_bgr, 2)

            # Draw label
            if show_labels:
                x1, y1, x2, y2 = det.bbox
                parts = [f"Otter #{det.otter_id + 1}"]
                if det.activity != "unknown":
                    parts.append(f"{det.activity} ({det.activity_conf:.0%})")
                if det.held_object != "none":
                    parts.append(f"holding: {det.held_object}")
                label = " | ".join(parts)

                (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
                cv2.rectangle(overlay, (x1, y1 - th - 10), (x1 + tw + 10, y1), color_bgr, -1)
                cv2.putText(overlay, label, (x1 + 5, y1 - 5),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1, cv2.LINE_AA)

        return overlay

    def is_loaded(self) -> bool:
        return self._loaded and self.model is not None
