"""
YOLO Trainer Module
Trains YOLOv8-seg on the YOLO-format dataset generated by data_prep.
Auto-scales to available hardware. Supports --sample for quick validation.
"""

import os
import shutil
import random
from pathlib import Path

from config import (
    YOLO_DATASET_DIR, MODEL_DIR, YOLO_MODEL_PATH, DEVICE,
    YOLO_BASE_MODEL, YOLO_BATCH_SIZE, YOLO_IMG_SIZE, YOLO_DEVICE,
    DATALOADER_WORKERS, HW_TIER
)


class YOLOTrainer:
    """Train YOLOv8-seg on otter segmentation data."""

    def __init__(self):
        self.model = None

    def _create_sampled_dataset(self, source_yaml: str, sample: float) -> str:
        """
        Create a smaller dataset by sampling a fraction of train/val.
        Returns path to the sampled dataset.yaml.
        """
        source_dir = Path(source_yaml).parent
        sample_dir = source_dir.parent / f"yolo_sample_{int(sample * 100)}pct"

        # If already exists from a previous run, reuse it
        if (sample_dir / "dataset.yaml").exists():
            train_count = len(list((sample_dir / "images" / "train").glob("*")))
            val_count = len(list((sample_dir / "images" / "val").glob("*")))
            print(f"[YOLOTrain] Reusing existing sample: {train_count} train, {val_count} val")
            return str(sample_dir / "dataset.yaml")

        print(f"[YOLOTrain] Creating {sample*100:.0f}% sample of dataset...")

        for split in ["train", "val"]:
            img_src = source_dir / "images" / split
            lbl_src = source_dir / "labels" / split
            img_dst = sample_dir / "images" / split
            lbl_dst = sample_dir / "labels" / split
            img_dst.mkdir(parents=True, exist_ok=True)
            lbl_dst.mkdir(parents=True, exist_ok=True)

            images = sorted([f for f in os.listdir(img_src) if f.endswith((".jpg", ".png"))])
            n = max(1, int(len(images) * sample))
            sampled = random.sample(images, n)

            for img_name in sampled:
                # Symlink instead of copy — instant, no disk usage
                img_file = img_src / img_name
                lbl_name = img_name.replace(".jpg", ".txt").replace(".png", ".txt")
                lbl_file = lbl_src / lbl_name

                os.symlink(str(img_file), str(img_dst / img_name))
                if lbl_file.exists():
                    os.symlink(str(lbl_file), str(lbl_dst / lbl_name))

            print(f"[YOLOTrain]   {split}: {n}/{len(images)} images")

        yaml_content = f"""path: {sample_dir}
train: images/train
val: images/val

names:
  0: otter
"""
        with open(sample_dir / "dataset.yaml", "w") as f:
            f.write(yaml_content)

        return str(sample_dir / "dataset.yaml")

    def train(
        self,
        dataset_yaml: str = str(YOLO_DATASET_DIR / "dataset.yaml"),
        epochs: int = 100,
        imgsz: int = None,
        batch: int = None,
        pretrained: str = None,
        sample: float = 1.0,
    ):
        if not os.path.exists(dataset_yaml):
            print(f"[YOLOTrain] Dataset config not found: {dataset_yaml}")
            print("[YOLOTrain] Run --prep-data first.")
            return

        # Create sampled dataset if needed
        if sample < 1.0:
            dataset_yaml = self._create_sampled_dataset(dataset_yaml, sample)

        imgsz = imgsz or YOLO_IMG_SIZE
        batch = batch or YOLO_BATCH_SIZE
        pretrained = pretrained or YOLO_BASE_MODEL

        from ultralytics import YOLO

        print(f"[YOLOTrain] Hardware tier: {HW_TIER.upper()}")
        print(f"[YOLOTrain] Base model:    {pretrained}")
        print(f"[YOLOTrain] Device:        {YOLO_DEVICE}")
        print(f"[YOLOTrain] Batch size:    {batch}")
        print(f"[YOLOTrain] Image size:    {imgsz}")
        print(f"[YOLOTrain] Epochs:        {epochs}")
        print(f"[YOLOTrain] Sample:        {sample*100:.0f}%")
        print(f"[YOLOTrain] Workers:       {DATALOADER_WORKERS}")

        self.model = YOLO(pretrained)

        results = self.model.train(
            data=dataset_yaml,
            epochs=epochs,
            imgsz=imgsz,
            batch=batch,
            device=YOLO_DEVICE,
            workers=DATALOADER_WORKERS,
            project=str(MODEL_DIR),
            name="yolo_seg_train",
            exist_ok=True,
            patience=20,
            save=True,
            plots=True,
            amp=HW_TIER in ("high", "medium"),
        )

        best_weights = Path(MODEL_DIR) / "yolo_seg_train" / "weights" / "best.pt"
        if best_weights.exists():
            shutil.copy(str(best_weights), str(YOLO_MODEL_PATH))
            print(f"[YOLOTrain] Best model saved to {YOLO_MODEL_PATH}")
        else:
            print("[YOLOTrain] Warning: best.pt not found after training.")

        return results

    def evaluate(self, dataset_yaml: str = str(YOLO_DATASET_DIR / "dataset.yaml")):
        if not os.path.exists(str(YOLO_MODEL_PATH)):
            print("[YOLOTrain] No trained model found. Train first.")
            return

        from ultralytics import YOLO

        model = YOLO(str(YOLO_MODEL_PATH))
        results = model.val(data=dataset_yaml, device=YOLO_DEVICE)
        print(f"[YOLOTrain] mAP50: {results.box.map50:.3f}")
        print(f"[YOLOTrain] mAP50-95: {results.box.map:.3f}")
        if hasattr(results, 'seg'):
            print(f"[YOLOTrain] Seg mAP50: {results.seg.map50:.3f}")
        return results