"""
YOLO Trainer Module
Trains YOLOv8-seg on the YOLO-format dataset generated by data_prep.
Auto-scales to available hardware.
"""

import os
from pathlib import Path

from config import (
    YOLO_DATASET_DIR, MODEL_DIR, YOLO_MODEL_PATH, DEVICE,
    YOLO_BASE_MODEL, YOLO_BATCH_SIZE, YOLO_IMG_SIZE, YOLO_DEVICE,
    DATALOADER_WORKERS, HW_TIER
)


class YOLOTrainer:
    """Train YOLOv8-seg on otter segmentation data."""

    def __init__(self):
        self.model = None

    def train(
        self,
        dataset_yaml: str = str(YOLO_DATASET_DIR / "dataset.yaml"),
        epochs: int = 100,
        imgsz: int = None,
        batch: int = None,
        pretrained: str = None,
    ):
        if not os.path.exists(dataset_yaml):
            print(f"[YOLOTrain] Dataset config not found: {dataset_yaml}")
            print("[YOLOTrain] Run --prep-data first.")
            return

        # Use auto-scaled defaults if not overridden
        imgsz = imgsz or YOLO_IMG_SIZE
        batch = batch or YOLO_BATCH_SIZE
        pretrained = pretrained or YOLO_BASE_MODEL

        from ultralytics import YOLO

        print(f"[YOLOTrain] Hardware tier: {HW_TIER.upper()}")
        print(f"[YOLOTrain] Base model:    {pretrained}")
        print(f"[YOLOTrain] Device:        {YOLO_DEVICE}")
        print(f"[YOLOTrain] Batch size:    {batch}")
        print(f"[YOLOTrain] Image size:    {imgsz}")
        print(f"[YOLOTrain] Epochs:        {epochs}")
        print(f"[YOLOTrain] Workers:       {DATALOADER_WORKERS}")

        self.model = YOLO(pretrained)

        results = self.model.train(
            data=dataset_yaml,
            epochs=epochs,
            imgsz=imgsz,
            batch=batch,
            device=YOLO_DEVICE,
            workers=DATALOADER_WORKERS,
            project=str(MODEL_DIR),
            name="yolo_seg_train",
            exist_ok=True,
            patience=20,
            save=True,
            plots=True,
            amp=HW_TIER in ("high", "medium"),  # Mixed precision on capable GPUs
        )

        best_weights = Path(MODEL_DIR) / "yolo_seg_train" / "weights" / "best.pt"
        if best_weights.exists():
            import shutil
            shutil.copy(str(best_weights), str(YOLO_MODEL_PATH))
            print(f"[YOLOTrain] Best model saved to {YOLO_MODEL_PATH}")
        else:
            print("[YOLOTrain] Warning: best.pt not found after training.")

        return results

    def evaluate(self, dataset_yaml: str = str(YOLO_DATASET_DIR / "dataset.yaml")):
        if not os.path.exists(str(YOLO_MODEL_PATH)):
            print("[YOLOTrain] No trained model found. Train first.")
            return

        from ultralytics import YOLO

        model = YOLO(str(YOLO_MODEL_PATH))
        results = model.val(data=dataset_yaml, device=YOLO_DEVICE)
        print(f"[YOLOTrain] mAP50: {results.box.map50:.3f}")
        print(f"[YOLOTrain] mAP50-95: {results.box.map:.3f}")
        if hasattr(results, 'seg'):
            print(f"[YOLOTrain] Seg mAP50: {results.seg.map50:.3f}")
        return results
